<?xml version="1.0" encoding="utf-8"?><Database Name="DB_ULTRAMEDICA" Class="db_ultramedicaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=USER-PC\SQLEXPRESS;Initial Catalog=DB_ULTRAMEDICA;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_ULTRAMEDICAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AUDIO" Member="AUDIOs">
    <Type Name="AUDIO">
      <Column Name="AUDIO_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="AUDIOMETRY_RESULT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AUDIOMETRY_FILE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKED_BY" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="FO_AUDIO" Member="FO" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.COMPANY" Member="COMPANies">
    <Type Name="COMPANY">
      <Column Name="COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="COMPANY_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="COMPANY_STATUS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="COMPANY_EMPLOYEE" Member="EMPLOYEEs" ThisKey="COMPANY_ID" OtherKey="COMPANY_ID" Type="EMPLOYEE" />
    </Type>
  </Table>
  <Table Name="dbo.EKG" Member="EKGs">
    <Type Name="EKG">
      <Column Name="EKG_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="EKG_RESULT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EKG_FILE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKED_BY" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="FO_EKG" Member="FO" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FO" Member="FOs">
    <Type Name="FO">
      <Column Name="LAB_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DISTRICT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="FO_AUDIO" Member="AUDIOs" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="AUDIO" />
      <Association Name="FO_EKG" Member="EKGs" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="EKG" />
      <Association Name="FO_RONTGEN" Member="RONTGENs" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="RONTGEN" />
      <Association Name="FO_SPIRO" Member="SPIROs" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="SPIRO" />
      <Association Name="FO_FISIK" Member="FISIKs" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FISIK" />
      <Association Name="FO_LAB" Member="LABs" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="LAB" />
      <Association Name="EMPLOYEE_FO" Member="EMPLOYEE" ThisKey="EMPLOYEE_ID" OtherKey="EMPLOYEE_ID" Type="EMPLOYEE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ROLE" Member="ROLEs">
    <Type Name="ROLE">
      <Column Name="ROLE_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ROLE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RONTGEN" Member="RONTGENs">
    <Type Name="RONTGEN">
      <Column Name="RONTGEN_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="RONTGEN_RESULT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="RONTGEN_FILE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKED_BY" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="FO_RONTGEN" Member="FO" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SPIRO" Member="SPIROs">
    <Type Name="SPIRO">
      <Column Name="SPIRO_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="SPIROMETRY_RESULT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SPIROMETRY_FILE_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHECKED_BY" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="FO_SPIRO" Member="FO" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EMPLOYEE" Member="EMPLOYEEs">
    <Type Name="EMPLOYEE">
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AGE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MESS_STATUS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="POSITION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DISTRICT" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DEPARTMENT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="COMPANY_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="STATUS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EMPLOYEE_FO" Member="FOs" ThisKey="EMPLOYEE_ID" OtherKey="EMPLOYEE_ID" Type="FO" />
      <Association Name="COMPANY_EMPLOYEE" Member="COMPANY" ThisKey="COMPANY_ID" OtherKey="COMPANY_ID" Type="COMPANY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[USER]" Member="USERs">
    <Type Name="USER">
      <Column Name="NIK" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAMA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="POSISI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ROLES" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MASTER_SELECT" Member="MASTER_SELECTs">
    <Type Name="MASTER_SELECT">
      <Column Name="KEY_SELECT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VALUE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TEXT" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FISIK" Member="FISIKs">
    <Type Name="FISIK">
      <Column Name="FISIK_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="TEMPAT_KERJA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="POSISI_KERJA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PAPARAN" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="METODE_KERJA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RIWAYAT_ASMA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_EPILEPSI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_LEPRA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_ANSIETAS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_DEPRESI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_DM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_PROSTAT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_HEMOROID" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_KELAMIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VAKSIN_HEPATITIS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_OPERASI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RIWAYAT_KECELAKAAN_KERJA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SUMMARY_RIWAYAT_PENYAKIT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="KEBIASAAN_ALKOHOL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="KEBIASAAN_OLAHRAGA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="KEBIASAAN_MEROKOK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="KEBIASAAN_NARKOBA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TINGGI_BADAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BERAT_BADAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BMI" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="LKR_DD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LKR_PRT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="T_SISTOL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="T_DIASTOL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NADI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RESPIRASI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VISUS_JAUH_TANPA_KACMATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="VISUS_JAUH_DENGAN" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="VISUS_DEKAT_TANPA_KACAMATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="VISUS_DEKAT_DENGAN_KACAMATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="BUTA_WARNA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ANAMNESA_KELUHAN_UTAMA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ANAMNESA_KELUHAN_TAMBAHAN" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MATA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TELINGA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HIDUNG" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MULUT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FARING" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TONSIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="THYROID" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LYMP_NODE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DADA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PERUT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HERNIA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ANUS" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PAYUDARA" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="VARICHES_HEMOROID" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="KULIT_KUKU" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PULMO_SIST_RESPIRASI" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="COR_SIST_CV" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HATI_LIEN_GIT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SUG" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SIST_REPROD" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EXTRIMITAS_ATAS" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="EXTRIMITAS_BAWAH" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OTOT_TULANG_LAIN" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BAU_MULUT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KARIES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TANGGAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SISA_AKAR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REFLEX_PATOLOGIS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PARESTESI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PARESE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LASSAGUESIGN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PATRICK_SIGN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CONTRA_PATRICK_SIGN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SUMMARY_KESIMPULAN" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CHECKED_BY" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="FO_FISIK" Member="FO" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LABS" Member="LABs">
    <Type Name="LAB">
      <Column Name="LABORATORIUM_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMPLOYEE_ID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="YEAR_CHECKUP" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="HB" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="HCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LEUKOSIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TROMBOSIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ERITROSIT" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="LED" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIFLIM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIFMON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIFGRAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HBSAG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AHBS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VDRL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CHOLESTEROL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRIGLISERIN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HDL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LDL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BUN" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="CREATINE" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="UA" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BSN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[2JPP]" Member="_2JPP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REDUKSI_PUASA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="REDUKSI_2JPP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WARNA_URINE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BJ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KETON" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BIL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NITRIT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EPITEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="URINE_LEKOSIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="URINE_ERITROSIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BAKTERI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SIL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KRISTAL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LAB_RESUME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CHECKED_BY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="FO_LAB" Member="FO" ThisKey="EMPLOYEE_ID,YEAR_CHECKUP" OtherKey="EMPLOYEE_ID,YEAR_CHECKUP" Type="FO" IsForeignKey="true" />
    </Type>
  </Table>
</Database>